In [1]:
import numpy as np
# sizes = [2,3,1]
sizes = [2,3,4,3,1]
len(sizes)

5

In [2]:
sizes[1:], sizes[:-1]

([3, 4, 3, 1], [2, 3, 4, 3])

In [3]:
list(zip(sizes[1:], sizes[:-1]))

[(3, 2), (4, 3), (3, 4), (1, 3)]

In [4]:
x = [np.random.randn(y,1) for y in sizes[1:]]
type(np.array(x, dtype=object))

numpy.ndarray

In [5]:
from NN import *
net = Network([2,3,1], verbose=True)
# print("W: ", net.weights,"\nB: ", net.biases)

Number of layers:  3
Layer sizes:  [2, 3, 1]
Size of matrix of weights:  [(3, 2), (1, 3)]
Size of matrix of biases:  [(3, 1), (1, 1)]


In [9]:
for w, b in zip(net.weights, net.biases):
    print("Weights [size -- ", w.shape, "]: \n", w.round(2), "\n")
    print("Biases [size -- ", b.shape, "]: \n", b.round(2),"\n")

Weights [size --  (3, 2) ]: 
 [[-1.74 -1.27]
 [ 0.56 -0.18]
 [ 0.03  0.53]] 

Biases [size --  (3, 1) ]: 
 [[-1.12]
 [-0.6 ]
 [ 0.07]] 

Weights [size --  (1, 3) ]: 
 [[-0.51 -0.2   1.03]] 

Biases [size --  (1, 1) ]: 
 [[2.26]] 

