In [2]:
import numpy as np
# sizes = [2,3,1]
sizes = [2,3,4,3,1]
len(sizes)

5

In [3]:
sizes[1:], sizes[:-1]

([3, 4, 3, 1], [2, 3, 4, 3])

In [4]:
list(zip(sizes[1:], sizes[:-1]))

[(3, 2), (4, 3), (3, 4), (1, 3)]

In [5]:
x = [np.random.randn(y,1) for y in sizes[1:]]
type(np.array(x, dtype=object))

numpy.ndarray

In [6]:
from NN import *
net = Network([2,3,1], verbose=True)
# print("W: ", net.weights,"\nB: ", net.biases)

Number of layers:  3
Layer sizes:  [2, 3, 1]
Size of matrix of weights:  [(3, 2), (1, 3)]
Size of matrix of biases:  [(3, 1), (1, 1)]


In [15]:
for w, b in zip(net.weights, net.biases):
    print("Weights [size -- ", w.shape, "]: \n", w.round(2), "\n")
    print("Biases [size -- ", b.shape, "]: \n", b.round(2),"\n")

Weights [size --  (3, 2) ]: 
 [[ 1.92 -0.28]
 [ 0.68 -0.31]
 [ 1.64 -0.1 ]] 

Biases [size --  (3, 1) ]: 
 [[ 0.01]
 [ 0.3 ]
 [-1.16]] 

Weights [size --  (1, 3) ]: 
 [[-0.56  0.3  -0.06]] 

Biases [size --  (1, 1) ]: 
 [[-0.69]] 

